language: python
python:
    - "3.7"
before_install:
    - sudo apt-get update -qq
    # - sudo apt-get install -qq python3-pygame
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - python -c 'import pygame'
    - python cx-build.py build
